### ISSUE TITLE
Error ao subir o servidor localmente: No directory at: /web/staticfiles/

### ISSUE THREAD

**Issue by lianker** [cuducos/bot-followers#11]
Quando tento subir o servidor usando  o comando `docker-compose run --rm django` um alerta aparece indicando a ausencia da pasta /web/staticfiles conforme abaixo.

```shell
System check identified no issues (0 silenced).
December 09, 2019 - 20:52:50
Django version 3.0, using settings 'web.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
/usr/local/lib/python3.8/site-packages/whitenoise/base.py:116: UserWarning: No directory at: /web/staticfiles/
  warnings.warn(u"No directory at: {}".format(root))
```
Quando tento acessar o endereço http://localhost:8000 a resposta é como se o servidor não estivesse rodando (Unable to connect)

Se eu uso o comando `docker-compose up django` o mesmo alerta é exibido, mas quando tento acessar a página recebo como resposta um 404.

rodei as migrations e segui o readme. Não sei se o alerta é responsavel pelo erro, mas esse é o passo a passo que testei aqui.

**Comment by cuducos** [comment]
Hum… belo ponto! A documentação é omissa nesse ponto mesmo. Vou explicar o que está acontecendo. Depois vemos como melhorar a documentação.

**Qual o problema?**

A mensagem de erro vem de um pacote chamado [WhiteNoise](http://whitenoise.evans.io/en/stable/):

```
/usr/local/lib/python3.8/site-packages/whitenoise/base.py:116: UserWarning: No directory at: /web/staticfiles/
  warnings.warn(u"No directory at: {}".format(root))
```

Esse pacote serve arquivos estáticos (imagens, JavaScript, CSS, por exemplo) de uma forma mais eficiente que o ciclo de requisição e resposta padrão Django, e ele só é usado em produção. Em outras palavras, creio que ele é automaticamente desativado quando ` DEBUG == True`.

**O que fazer?**

Então, primeira sugestão que faço é: presumindo que, por rodar com Docker Compose, você está subindo a aplicação no modo _desenvolvimento_, o ideal seria ter `DEBUG=True` — como está teu `.env`?

Uma alternativa "gambiarra" seria _coletar os estáticos_ com `docker-compose run --rm django python manage.py collectstatic` — aí a pasta `staticfiles` existiria e o WhiteNoise, acho, não reclamaria. Mas ainda acho que em ambiente de desenvolvimento usarmos `DEBUG=True` seja a melhor escolha.

Tem como confirmar o valor de `DEBUG` para a gente ver se é isso mesmo?

> (Sei que no `.env.sample` o padrão é `DEBUG=False`; a princípio faço isso por segurança, para evitar que por descuido um ambiente vá para produção com `DEBUG=True`, pois isso pode ser uma brecha feia: as telas de erro com o modo `DEBUG` ativado exporiam, para o mundo, a `SECRET_KEY`, senha do banco de dados etc.)

**Comment by lianker** [comment]
Ao verificar o arquivo **.env** encontrei o valor  `DEBUG=false`. Alterei para `DEBUG=true` passou a funcionar e deixou de exibir alertas. Neste caso só consigo acessar usando o comando `docker-compose up django`. Com isso já é possível seguir.

Quando uso o comando `docker-compose run --rm django` continuo recebendo **Unable to connect** como resposta no navegador.

**Comment by cuducos** [comment]
> Quando uso o comando `docker-compose run --rm django` continuo recebendo Unable to connect como resposta no navegador.

Isso é esperado. Da [documentação do Docker Compose](https://docs.docker.com/compose/reference/run/):

> Commands you use with `run` start in new containers with configuration defined by that of the service, including volumes, links, and other details. However, there are two important differences.
> 
> First, [...]
>
> The second difference is that the `docker-compose run` command **does not create any of the ports** specified in the service configuration. (emphasis added)

Então acho que essa issue pode gerar duas formas de melhoria na documentação:

1. Ser claro quanto a usar `DEBUG=True` no ambiente de desenvolvimento (sem mudar o padrão do `.env.sample` para `False`, por segurança)
2. Ser claro quando a usar `docker-compose up` ao invés de `docker-compose run --rm django` para subir a aplicação

Faz sentido? Quais alterações no texto do `README.md` podem ser feitas quanto a isso?

**Comment by lianker** [comment]
Vi que no tópico [Development setup](https://github.com/cuducos/bot-followers#development-setup) já está presente o comando `docker-compose up` e o que confundiu foi o título **Usage** na sessão que indica os outros comandos, mas não sei se isso aconteceria com outras pessoas que ja possuem familiaridades com o django,

Para o item:
> 1. Ser claro quanto a usar DEBUG=True no ambiente de desenvolvimento (sem mudar o padrão do .env.sample para False, por segurança)

Pensei em adicionar ao final do tópico **Development setup** a observação.

> To prevent errors in local environment, change value to `DEBUG=true` in `.env` file 

Caso não possua nenhum outro ajuste posso fazer o PR.

**Comment by cuducos** [comment]
> To prevent errors in local environment, change value to DEBUG=true in .env file

It looks like a good idea. May we have `DEBUG=True` to be aligned with Python's `True`?
