### ISSUE TITLE
Update ImportError message in the manage.py file

### ISSUE THREAD

**Issue by ghost** [cuducos/bot-followers#15]
Hello, I would like to update the ImportError message in the manage.py file to make it more user-friendly. 

Could you please assign this to me?

**Comment by cuducos** [comment]
> Could you please assign this to me?

No. This file is an auto-generated one. If the idea is to change this sentence, I would prefer to have it changed in [Django](https://github.com/django/django/blob/main/django/conf/project_template/manage.py-tpl) instead.
